### ISSUE TITLE
Where can I find the code for ldap_context object?

### ISSUE THREAD

**Issue by sergei3000** [OpenVPN/openvpn-build#106]
I am looking into a bug in my logging system.
I have read this explanation about post_auth:
https://docs.openvpn.net/docs/access-server/openvpn-access-server-post-auth-scripting.html
I would like to understand what `ldap_context` object is doing, especially in this part of the example script in `pas.py`:
`l.search_ext_s(user_dn, ldap.SCOPE_SUBTREE, attrlist=["memberOf"])`
Where can I find the source code for that "ldap_context (object) -- ... a Python LDAP context object" which is written about in that article?

The bug I am looking into is this error I get when `user_dn` contains cyrillic letters:
`AUTH_RETURN`
`   status : FAIL`
`   reason : post_auth script failed: 'ascii' codec can't encode `
`characters in position 3-9: ordinal not in range(128): `
`python/threadpool:210,python/context:59,python/context:37,auth/authdelegate:154,<string>:153,ldap/ldapobject:590,ldap/ldapobject:586,ldap/ldapobject:106 `
`(exceptions.UnicodeEncodeError)`

As far as I can see from our logs, the problem appears in this part of the script in the definition of the `post_auth`:
`ldap_groups = ldap_groups_parse(l.search_ext_s(user_dn, ldap.SCOPE_SUBTREE, attrlist=["memberOf"]))`

I tried to use this hack in my script:
`import sys`
`reload(sys)`
`sys.setdefaultencoding('UTF8')`
but everything just breaks after that, so I quit using this hack.

Please point me to the source code of the `ldap_context` object or/and advise on the problem itself.
Thank you.

**Comment by mattock** [comment]
@sergei3000 : you should ask this question in [Access Server support system](https://openvpn.net/index.php/login.html). Here we only discuss things related to OpenVPN's cross-compile buildsystem.
