### ISSUE TITLE
compile is not working with openssl 1.1.0f

### ISSUE THREAD

**Issue by andyVSR** [OpenVPN/openvpn-build#107]
if i try to cross compile with openssl 1.1.0f and openvpn 2.4.3, i get :
 unsupported options: no-multilib
 FATAL: Configure openssl
i know that openvpn version 2.4.3 does support openssl 1.1.0.

**Comment by chipitsine** [comment]
I spent some time on getting openvpn-build working with openssl-1.1.0, no luck yet.

PR is welcome

**Comment by andyVSR** [comment]
Maybe you can get some help from dd-wrt dev BS. Latest dd-wrt has openvpn 2.4.3 and openssl 1.1.0f. 
 When i will have time i will take a look on his configuration files on http://svn.dd-wrt.com/browser/src/router/openssl and openvpn.

**Comment by chipitsine** [comment]
@andyVSR : can you send a PR ?

**Comment by mattock** [comment]
This has been fixed as OpenVPN 2.4.5 is now built with OpenSSL 1.1.0f by default.
