### ISSUE TITLE
automatic snapshot releases 

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#113]
@mattock, what do you think about https://github.com/chipitsine/openvpn-build/commit/509ab6ef8b38bf63f2d2226cf2f6ba089975fc82 ?

I cannot make a PR, there are specific tokens (and they were enabled by "travis setup releases")

it is a step to "cloud releases" instead of build.openvpn.net, we can sign, publish tag releases, etc, etc, etc

as a first step I would enable snapshot releases (like the one in the above commit), it will allow automatic testing of windows installers (as they are published on cron builds)

**Comment by mattock** [comment]
@chipitsine : while we do produce [snapshot builds](https://github.com/OpenVPN/openvpn-windows-buildtest) already, I think having Travis build snapshots is a good idea. Especially as Travis can build the installers from PRs also. Such test installers don't need to be signed imho.

**Comment by chipitsine** [comment]
@mattock , travis-ci does not expose encrypted variables to PR builds. Neither Travis keeps artifacts by itself.

So, I do not think of PR builds. But anyway, Travis snapshot releases seem to be good, github allows to get the latest release. I will implement CI on top of that, I.e. get the latest release, test it with openvpn-windows-test

**Comment by flichtenheld** [comment]
obsolete. We now have proper snapshots with GHA
