### ISSUE TITLE
why snapshots are built without lzo, lz4 ?

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#115]
https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/build-snapshot#L35

any special purpose of that ?

**Comment by mattock** [comment]
Hmm, not sure. Does it build fine with --disable-lzo and --disable-lz4 removed?

**Comment by mattock** [comment]
@chipitsine : ok.

**Comment by flichtenheld** [comment]
those snapshots don't exist anymore
