### ISSUE TITLE
We should upgrade openssl to 1.1.0g+ for building Windows binary

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-build#123]
SSL_CTX_set_max/min_proto_version() and the corresponding getters are not compatible when built with 1.1 prior to 1.1.0g because those versions define the setters but not the getters. (1.0 is fine as neither is defined). This leads to using setters from the library and getters from the compat layer meant for 1.0. 
It seems the  only ill effect is less than ideal error messages in some rare cases[*], but it would be much better to use 1.1.0g (or newer when available) for the next release.

**Comment by chipitsine** [comment]
it is easy, except app veyor

**Comment by mattock** [comment]
I can definitely make an Windows installer-only release next week or so. It would be nice to get some of the openvpn-gui improvements into it, though, not just upgraded OpenSSL.

**Comment by selvanair** [comment]
OK, this is not that critical, so let's see whether we can add some more stuff to the GUI before a new release.
By the way, we keep adding new features to the GUI but do not document them well. I wish we had a page that documents the GUI in its post interactive-service form. Then it would be easier to keep it updated as we add new stuff. Old pages like https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI are so outdated. May be we could ask for help from users?

**Comment by mattock** [comment]
@selvanair It seems we have several changes/fixes pending for the next Windows release, so let's tackle all of them in one go, if possible.

Historically asking for help on OpenVPN mailing lists has not worked that well. I think we should try asking for help here using a GitHub issue. Having some concrete tasks would help get people interested. Anything in particular in mind?

**Comment by TinCanTech** [comment]
Dear reader, we now have a new GUI page:
https://community.openvpn.net/openvpn/wiki/OpenVPN-GUI-New

**Comment by flichtenheld** [comment]
obsolete issue
