### ISSUE TITLE
OpenVPN 2.4.5 static linking on Linux/MacOS 

### ISSUE THREAD

**Issue by berserker** [OpenVPN/openvpn-build#124]
I tested openvpn-build with openvpn 2.4.5 / openssl-1.1.0f and I can confirm that the DO_STATIC=1 switch doesn't work as expected (libcrypto and libssl **are always linked dynamically**).
I managed to get a static build of openvpn by adding the "-static" flat to EXTRA_OPENSSL_CONFIG param.

**Comment by berserker** [comment]
An additional note for the problem on MacOS: building with "-static" (required by openssl 1.1.x) causes [this problem](https://software.intel.com/en-us/articles/library-not-found-crt0) so I had to hack the build script and comment out the line "EX_LIBS = -static" generated in the openssl's Makefile.

**Comment by chipitsine** [comment]
well, we can add osx builds to travis-ci matrix if those are really needed

**Comment by chipitsine** [comment]
@berserker - do you know easy way of determing dynamic linking under travis-ci ?

**Comment by berserker** [comment]
Thanks for the feedback @chipitsine but unfortunately I'm not familiar with travis-ci.
Let me know if I can help you in another way :thumbsup:

**Comment by chipitsine** [comment]
Travis-ci is either Linux or osx build agents

We already use it http://travis-ci.org/OpenVPN/openvpn-build

According to your findings, it seems those build scripts should be modified

**Comment by chipitsine** [comment]
well, what if we will check  ${CHOST}-objdump

openssl-1.0.2:

```
i686-w64-mingw32-objdump -p ./generic/image/openvpn/bin/openvpn.exe |grep DLL
 vma:            Hint    Time      Forward  DLL       First
	DLL Name: ADVAPI32.dll
	DLL Name: CRYPT32.dll
	DLL Name: fwpuclnt.dll
	DLL Name: GDI32.dll
	DLL Name: IPHLPAPI.DLL
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: ncrypt.dll
	DLL Name: USER32.dll
	DLL Name: WS2_32.dll
```

openssl-1.1.0:

```
i686-w64-mingw32-objdump -p ./generic/image/openvpn/bin/openvpn.exe |grep DLL
 vma:            Hint    Time      Forward  DLL       First
	DLL Name: libcrypto-1_1.dll
	DLL Name: libssl-1_1.dll
	DLL Name: ADVAPI32.dll
	DLL Name: CRYPT32.dll
	DLL Name: fwpuclnt.dll
	DLL Name: IPHLPAPI.DLL
	DLL Name: KERNEL32.dll
	DLL Name: msvcrt.dll
	DLL Name: ncrypt.dll
	DLL Name: USER32.dll
	DLL Name: WS2_32.dll
```

**Comment by flichtenheld** [comment]
Moving the MinGW builds of OpenVPN to use CMake+VCPKG. Support is already in master and will be backported to release/2.6. There is definitely no plan to address this in the context of "generic". So closing this issue.
