### ISSUE TITLE
configure: error: man2html is required for win32

### ISSUE THREAD

**Issue by David699** [OpenVPN/openvpn-build#126]
Build in Cygwin:   IMAGEROOT=`pwd`/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=i686-pc-cygwin ./build  
 
Then error:
configure: error: man2html is required for win32

System: Win10 64bit

**Comment by David699** [comment]
checking for man2html... no
configure: error: man2html is required for win32
FATAL: Configure pkcs11-helper

**Comment by chipitsine** [comment]
man2html is required on any system, not only win32. it is how "configure" supposed to work - it checks all the requirements and fails if something goes wrong

**Comment by David699** [comment]
It seems there is no  man2html package in cygwin, any solution?

**Comment by chipitsine** [comment]
I did dirty hack within AppVeyor build script:

https://github.com/OpenVPN/openvpn-build/blob/master/.appveyor.yml#L15


let me know if you'll find better solution

**Comment by David699** [comment]
https://github.com/OpenVPN/openvpn-build/blob/master/.appveyor.yml#L15

How to use this when building?

**Comment by chipitsine** [comment]
```cp `which true` /usr/bin/man2html'```

means "copy true to man2html". "true" will return 200

**Comment by David699** [comment]
Thanks！ I thank  this should be added in https://github.com/OpenVPN/openvpn-build/blob/master/generic/README,  so others can see it when build in cygwin.

**Comment by David699** [comment]
Thanks very much for your help！

**Comment by mattock** [comment]
I documented the workaround in [openvpn-build wiki documentation](https://community.openvpn.net/openvpn/wiki/SettingUpGenericBuildsystem).
