### ISSUE TITLE
TMPDIR should not be a subdirectory of $(pwd)

### ISSUE THREAD

**Issue by qdii** [OpenVPN/openvpn-build#128]
https://github.com/OpenVPN/openvpn-build/blob/be29cd5c7575da438783bd11412c04f32dfde28c/windows-nsis/build-complete#L19

According to the [UNIX specification](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03):

> [TMPDIR is] a pathname of a directory made available for programs that need a place to create temporary files.

I don't see why IMAGEROOT should be under `$(pwd)`. `$(pwd)` has no guarantee to have enough space or even be writeable. It sounds to me that a subdirectory of `TMPDIR` should be used instead.

**Comment by flichtenheld** [comment]
NSIS installer is not supported anymore. Closing issues.
