### ISSUE TITLE
Cross compiling for Windows fails

### ISSUE THREAD

**Issue by ac130kz** [OpenVPN/openvpn-build#133]
System: Xubuntu 18.04 with mingw-w64 installed
openvpn-build commit 62383bdb078ec435dacb5ae685a19bc968933daa

I applied the following changes to build.vars and ran ./build
```
CHOST=x86_64-w64-mingw32
CBUILD=x86_64-pc-linux-gnu
IMAGEROOT=`pwd`/image-win64
```
[Crash log](https://gist.github.com/ac130kz/09368f4f13665396c5516b07872dd910)

**Comment by flichtenheld** [comment]
We have decided to remove the nsis/mingw buildsystem since it is not maintained anymore. Only the msi/msvc buildsystem will remain, unless someone steps up to maintain the other parts. This issue will be closed when the removal actually happens.

**Comment by flichtenheld** [comment]
Moving the MinGW builds of OpenVPN to use CMake+VCPKG. Support is already in master and will be backported to release/2.6. There is definitely no plan to address this in the context of "generic". So closing this issue.
