### ISSUE TITLE
Exception   KernelBase.dll    access denied

### ISSUE THREAD

**Issue by lmhsky** [OpenVPN/openvpn-build#143]
“openvpnserv.exe”(Win32): 已加载“C:\openvpn-build\msvc\build.tmp\openvpn-master\x64-Output\Debug\openvpnserv.exe”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\userenv.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\IPHLPAPI.DLL”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\FWPUCLNT.DLL”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\profapi.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\netapi32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\windows.storage.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140d.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\ucrtbased.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\netutils.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\samcli.dll”。已加载符号。
“openvpnserv.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。已加载符号。
0x00007FFFFED74048 (KernelBase.dll)处(位于 openvpnserv.exe 中)引发的异常: 0x00000005: 拒绝访问。。
线程 0xc38 已退出，返回值为 0 (0x0)。
线程 0x2e1c 已退出，返回值为 0 (0x0)。
线程 0x2ddc 已退出，返回值为 0 (0x0)。
程序“[9308] openvpnserv.exe”已退出，返回值为 0 (0x0)。

**Comment by sarahBenzaquen** [comment]
Hi , did you resolve the issue please? , I have the same

**Comment by flichtenheld** [comment]
This issue is too old to be useful. If you still have problems, please open a new issue.
