### ISSUE TITLE
build-complete broken

### ISSUE THREAD

**Issue by ikreb7** [OpenVPN/openvpn-build#147]
I use the latest master branch and run ``./build-complete``. I get this error message:

    Build openvpn
    ../generic/build: 256: cd: can't cd to openvpn-build/windows-nsis/tmp/build-i686/openvpn-2.4.7
    FATAL: cd openvpn
    FATAL: build i686 >&2

**Comment by flichtenheld** [comment]
Moving the MinGW builds of OpenVPN to use CMake+VCPKG. Support is already in master and will be backported to release/2.6. There is definitely no plan to address this in the context of "generic". So closing this issue.
