### ISSUE TITLE
error occurred while compiling on Ubuntu 18.04 

### ISSUE THREAD

**Issue by GUTIREZ** [OpenVPN/openvpn-build#156]
error occurred when i run commands below, may i know how to fix this?

==== compile command(both of the commands throw the same error)
== command 1
$ cd openvpn-build/generic
$  IMAGEROOT=`pwd`/image-win32 CHOST=i686-w64-mingw32 \
    CBUILD=x86_64-pc-linux-gnu ./build

==command 2
$ cd openvpn-build/windows-nsis
$ ./build-snapshot

==== error message
....
i686-w64-mingw32-windres -DHAVE_CONFIG_H -I. -I../.. -I../../include  -I../../include -I../../src/compat -DWIN32_LEAN_AND_MEAN -DNTDDI_VERSION=NTDDI_VISTA -D_WIN32_WINNT=_WIN32_WINNT_VISTA -i "openvpn_win32_resources.rc" -o "openvpn_win32_resources.o"
i686-w64-mingw32-gcc -DHAVE_CONFIG_H -I. -I../.. -I../../include  -I../../include -I../../src/compat -DWIN32_LEAN_AND_MEAN -DNTDDI_VERSION=NTDDI_VISTA -D_WIN32_WINNT=_WIN32_WINNT_VISTA -I/home/workspace/openvpn/openvpn-build/generic/image-win32/openvpn/include -I/home/workspace/openvpn/openvpn-build/generic/image-win32/openvpn/include -I/home/workspace/openvpn/openvpn-build/generic/image-win32/openvpn/include  -I/home/workspace/openvpn/openvpn-build/generic/image-win32/openvpn/include -DPLUGIN_LIBDIR=\"//lib/openvpn/plugins\" -municode -UUNICODE -Wall -Wno-unused-parameter -Wno-unused-function  -Wl,--dynamicbase,--nxcompat  -std=c99 -MT block_dns.o -MD -MP -MF .deps/block_dns.Tpo -c -o block_dns.o block_dns.c
mv -f .deps/tun.Tpo .deps/tun.Po
In file included from buffer.h:28:0,
                 from cryptoapi.c:50:
cryptoapi.c: In function ‘priv_enc_CNG’:

- [ ] cryptoapi.c:230:28: error: ‘CERT_NCRYPT_KEY_SPEC’ undeclared (first use in this function)
- [ ]      ASSERT(cd->key_spec == CERT_NCRYPT_KEY_SPEC);
- [ ]                             ^
- [ ] error.h:221:30: note: in definition of macro ‘ASSERT’
- [ ]  #define ASSERT(x) do { if (!(x)) {assert_failed(__FILE__, __LINE__, #x);}} while (false)
                              ^
cryptoapi.c:230:28: note: each undeclared identifier is reported only once for each function it appears in
     ASSERT(cd->key_spec == CERT_NCRYPT_KEY_SPEC);
                            ^
error.h:221:30: note: in definition of macro ‘ASSERT’
 #define ASSERT(x) do { if (!(x)) {assert_failed(__FILE__, __LINE__, #x);}} while (false)
                              ^
cryptoapi.c: In function ‘rsa_priv_enc’:
cryptoapi.c:270:25: error: ‘CERT_NCRYPT_KEY_SPEC’ undeclared (first use in this function)
     if (cd->key_spec == CERT_NCRYPT_KEY_SPEC)
                         ^
cryptoapi.c: In function ‘finish’:
cryptoapi.c:430:29: error: ‘CERT_NCRYPT_KEY_SPEC’ undeclared (first use in this function)
         if (cd->key_spec == CERT_NCRYPT_KEY_SPEC)
                             ^
cryptoapi.c: In function ‘SSL_CTX_use_CryptoAPI_certificate’:
cryptoapi.c:575:21: error: ‘CRYPT_ACQUIRE_PREFER_NCRYPT_KEY_FLAG’ undeclared (first use in this function)
                   | CRYPT_ACQUIRE_PREFER_NCRYPT_KEY_FLAG;
                     ^
cryptoapi.c:591:28: error: ‘CERT_NCRYPT_KEY_SPEC’ undeclared (first use in this function)
         && cd->key_spec != CERT_NCRYPT_KEY_SPEC)
                            ^
Makefile:674: recipe for target 'cryptoapi.o' failed
make[4]: *** [cryptoapi.o] Error 1
make[4]: *** Waiting for unfinished jobs....
...

**Comment by mattock** [comment]
Was your build environment setup with the [automated script](https://community.openvpn.net/openvpn/attachment/wiki/SettingUpGenericBuildsystem/setup-generic-buildsystem.7.sh) (from [here](https://community.openvpn.net/openvpn/wiki/SettingUpGenericBuildsystem))?
