### ISSUE TITLE
It seems that there is no way to build windows x86

### ISSUE THREAD

**Issue by what951006** [OpenVPN/openvpn-build#164]
I changed build bat to x86 ,but it seems to run failed , build.bat quit without any errors, how can I build a x86 openvpn?? thanks first

**Comment by rozmansi** [comment]
The build.bat is hardcoded to build AMD64 only, as MSVC building was/is designed for development only - not the final building of redistributables.

**Comment by flichtenheld** [comment]
This should be fixed
