### ISSUE TITLE
Binary for Win10

### ISSUE THREAD

**Issue by amplatzer** [OpenVPN/openvpn-build#165]
Hi Guys,
Is there any way to build installer for Win10, like the one on  Openvpn.net.  openvpn-install-2.4.7-I607-Win10.exe

Thanks,
Joey

**Comment by mattock** [comment]
Yes there is. The only difference to Windows 7 installers is that WIndows 10 needs an attestation signed tap-windows6 driver. Essentially, you'd use this as the tap-windows6 installer URL:

* https://build.openvpn.net/downloads/releases/tap-windows-9.24.2-I601-Win10.exe

The actual signing process for the driver [is rather convoluted](https://github.com/OpenVPN/tap-windows6#release-signing) but you don't have to worry about it, unless you want to build tap-windows6 as well.
