### ISSUE TITLE
build fail on win10

### ISSUE THREAD

**Issue by yixuan0719** [OpenVPN/openvpn-build#174]
cl  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MD /W3 /wd4090 /nologo /O2 /I "." /I "include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_IA32_SSE2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_MONT5" -D"OPENSSL_BN_ASM_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"KECCAK1600_ASM" -D"RC4_ASM" -D"MD5_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"GHASH_ASM" -D"ECP_NISTZ256_ASM" -D"X25519_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\"D:\\openvpn-32client\\openvpn-build\\msvc\\image\\ssl\"" -D"ENGINESDIR=\"D:\\openvpn-32client\\openvpn-build\\msvc\\image\\lib\\engines-1_1\"" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"OPENSSL_USE_APPLINK" -D"NDEBUG"  /Zs /showIncludes "crypto\dllmain.c" 2>&1 > crypto\dllmain.d
        "C:\Strawberry\perl\bin\perl.exe" "util\mkrc.pl" libcrypto > libcrypto.rc
        1  /folibcrypto.res "libcrypto.rc"
'1' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
NMAKE : fatal error U1077: “1”: 返回代码“0x1”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
FAILED

**Comment by yixuan0719** [comment]
It seems something wrong when exec the perl script, i have no way to resolve it.

**Comment by yixuan0719** [comment]
I git clone the code and just run "build.bat", pop up error info:
![图片](https://user-images.githubusercontent.com/45752835/82410246-11aab100-9aa2-11ea-8ae0-c5fd4ea1de38.png)
my OS is:
![图片](https://user-images.githubusercontent.com/45752835/82410303-2ab36200-9aa2-11ea-9112-b008845db256.png)

Does someone meet this issue before?

**Comment by yixuan0719** [comment]
The strawberry installed is:
![图片](https://user-images.githubusercontent.com/45752835/82410434-78c86580-9aa2-11ea-940d-d522cba50540.png)

**Comment by mattock** [comment]
I never build with openvpn-build/msvc. @lstipakov did/does, maybe he has some ideas.

**Comment by lstipakov** [comment]
Do you use build.bat from openvpn-build?

If not, this might be related:
```
rem OpenSSL build defines RC as "1" when undefined on some environments.
if "%RC%"=="" SET RC=rc
```

**Comment by yixuan0719** [comment]
Hi, all:
  I have compiled the openvpn in the 32bit system, by running the build.bat in the msvc directory,  i will try to rem "if "%RC%"=="" SET RC=rc".


  Thanks all very much.
















At 2020-05-22 17:31:42, "Lev Stipakov" <notifications@github.com> wrote:

Do you use build.bat from openvpn-build?

If not, this might be related:

rem OpenSSL build defines RC as "1" when undefined on some environments.
if "%RC%"=="" SET RC=rc

**Comment by flichtenheld** [comment]
This issue is too old be useful, please reopen with current information if you still have the problem.
