### ISSUE TITLE
build script error!

### ISSUE THREAD

**Issue by btwise** [OpenVPN/openvpn-build#179]
in `windows-nsis/build` script, because the `tmp/installer/openvpn/share/doc/license` file has not been created, so the `text () `function should be put in the order of the license file creation is completed, Because it cannot find `tmp/script installer/openvpn/share/doc` file folder and terminate the exit!
Please fix it!

**Comment by flichtenheld** [comment]
We have decided to remove the nsis/mingw buildsystem since it is not maintained anymore. Only the msi/msvc buildsystem will remain, unless someone steps up to maintain the other parts. This issue will be closed when the removal actually happens.

**Comment by flichtenheld** [comment]
NSIS installer is not supported anymore. Closing issues.
