### ISSUE TITLE
Windows 10 Build Error 

### ISSUE THREAD

**Issue by sreekupm** [OpenVPN/openvpn-build#180]
Hi, 
unable to build please help.

Please find the below details 

FinalizeBuildStatus:
  Deleting file "x64\Release\openvpnmsica.tlog\unsuccessfulbuild".
  Touching "x64\Release\openvpnmsica.tlog\openvpnmsica.lastbuildstate".
Done Building Project "C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnmsica\openvpnmsica.vcxproj" (default targets).

Done Building Project "C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\openvpn.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\openvpn.sln" (default target) (1) ->
"C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj" (default target) (2) ->
(ClCompile target) ->
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\automatic.c(140,16): warning C4996: 'wcscpy': This function or variable may be unsafe. Consider using wcscpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN
GS. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\automatic.c(157,20): warning C4996: 'wcscat': This function or variable may be unsafe. Consider using wcscat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN
GS. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\automatic.c(158,20): warning C4996: 'wcscat': This function or variable may be unsafe. Consider using wcscat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNIN
GS. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\common.c(40,15): warning C4996: '_vsnwprintf': This function or variable may be unsafe. Consider using _vsnwprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_
WARNINGS. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\common.c(314,9): warning C4996: 'wcsncpy': This function or variable may be unsafe. Consider using wcsncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS
. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\interactive.c(883,19): warning C4996: 'wcsdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _wcsdup. See online help for
details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\interactive.c(1051,9): warning C4996: 'wcsncat': This function or variable may be unsafe. Consider using wcsncat_s instead. To disable deprecation, use _CRT_SECURE_NO_WA
RNINGS. See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\interactive.c(1147,29): warning C4996: 'wcsdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _wcsdup. See online help for
 details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\service.c(71,12): warning C4996: 'wcscat': This function or variable may be unsafe. Consider using wcscat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
 See online help for details. [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpnserv\openvpnserv.vcxproj]

"C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\openvpn.sln" (default target) (1) ->
"C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\lzo.h(42,10): fatal error C1083: Cannot open include file: 'lzo/lzoutil.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\lzo.h(42,10): fatal error C1083: Cannot open include file: 'lzo/lzoutil.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\lzo.h(42,10): fatal error C1083: Cannot open include file: 'lzo/lzoutil.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\cryptoapi.c(42,10): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\ope
nvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\lzo.h(42,10): fatal error C1083: Cannot open include file: 'lzo/lzoutil.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\pkcs11.c(34,10): fatal error C1083: Cannot open include file: 'pkcs11-helper-1.0/pkcs11h-certificate.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-
openvpn\src\openvpn\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\ssl_verify_openssl.h(33,10): fatal error C1083: Cannot open include file: 'openssl/x509.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\o
penvpn\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\ssl_verify_openssl.h(33,10): fatal error C1083: Cannot open include file: 'openssl/x509.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\o
penvpn\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\ssl_verify_openssl.h(33,10): fatal error C1083: Cannot open include file: 'openssl/x509.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\o
penvpn\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\crypto_openssl.h(32,10): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvp
n\openvpn.vcxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]
  C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\tun.h(29,10): fatal error C1083: Cannot open include file: 'tap-windows.h': No such file or directory [C:\Users\Sreekumar\Desktop\openvpn-build-openvpn\src\openvpn\openvpn.v
cxproj]

    9 Warning(s)
    48 Error(s)

Time Elapsed 00:00:52.38
FAILED

**Comment by lstipakov** [comment]
Missing `tap-windows6.h` means that this specific dependency is not installed. As for now, dependencies are handled by vcpkg and should be installed automatically before build. Could you try again with the latest sources?

**Comment by flichtenheld** [comment]
This issue is too old to be useful.
