### ISSUE TITLE
OpenSSL 1.1.1h

### ISSUE THREAD

**Issue by Neustradamus** [OpenVPN/openvpn-build#194]
OpenSSL 1.1.1h is out yesterday
- https://www.openssl.org/

**Comment by mattock** [comment]
A new OpenVPN 2.5 release will be out in a week or two. I'll bundle that with 1.1.1h.

**Comment by Neustradamus** [comment]
@mattock: Thanks, it is important to have the latest libraries (it is for all OpenVPN sourcecodes).
When it is ok, please inform here the commit.

**Comment by mattock** [comment]
I updated generic/build.vars. The changes will appear in the next release.
