### ISSUE TITLE
Modifying Window names, and icons in Visual Studio

### ISSUE THREAD

**Issue by kbencze95** [OpenVPN/openvpn-build#199]
I want to change certain elements of the GUI, with Visual Studio.
These are names of two windows, and also the icons next to them. 
To make it obvious, I marked them on this picture:
![openvpn](https://user-images.githubusercontent.com/42838737/97973776-e2290000-1dc6-11eb-99f3-781c8c96f791.jpg)

Where can I find the strings, and icons, which I need to modify?
Thanks in advance!

**Comment by mattock** [comment]
This is not really a question for openvpn-build, but for [openvpn-gui](https://github.com/OpenVPN/openvpn-gui). Once you've made the GUI modifications you need to build a custom openvpn-gui-<version>.tar.gz, place it on a webserver and point openvpn-build to it.
