### ISSUE TITLE
Windows NSIS installer and Easy-RSA 3

### ISSUE THREAD

**Issue by TinCanTech** [OpenVPN/openvpn-build#225]
I recently had to build Openvpn for Windows and I use NSIS because there are less dependencies.
Unfortunately, this still only packages Easy-RSA v2.

Are there plans to upgrade this to Easy-RSA v3 ?

**Comment by cron2** [comment]
Hi,

On Wed, Aug 25, 2021 at 06:25:15AM -0700, TinCanTech wrote:
> I recently had to build Openvpn for Windows and I use NSIS because there are less dependencies.
> Unfortunately, this still only packages Easy-RSA v2.
> 
> Are there plans to upgrade this to Easy-RSA v3 ?

I do not think anyone would object.  

Someone needs to do the work, though - so: please send patch.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by TinCanTech** [comment]
I have looked into it sometime ago but at that time Openvpn had not decided to ship EasyRSA-3.
I'll take another look at it and see what I can do.
