### ISSUE TITLE
[Feature] Make the Docker image official

### ISSUE THREAD

**Issue by patsevanton** [OpenVPN/openvpn-build#262]
Please Make this an official Docker image: https://docs.docker.com/docker-hub/official_images/

Official images are easier to adopt in corporate environments where there are can be that strict rules about what docker images can be used out of the box.

**Comment by cron2** [comment]
What would "this" be, in this context?

openvpn-build is the build environment for openvpn, not much good in dockerizing this...

Spamming all repos for "yeah, docker is cool, please make docker images", no matter what the repo is about?

**Comment by patsevanton** [comment]
I am sorry. May be create issue in incorrect repo. Where can i create issue for create docker official image?

**Comment by cron2** [comment]
a docker image for what?

**Comment by patsevanton** [comment]
Docker image for openvpn-server

**Comment by cron2** [comment]
After checking with my co-volunteers, we found that the OpenVPN project does not provide any docker images at all, neither official nor inofficial.  We do provide operating system packages (deb, rpm).

**Comment by mattock** [comment]
If somebody volunteers to create a Docker image for OpenVPN 2.x server then we would consider doing what you propose and making it official. None of the current developers / users have felt the pain acutely enough to do it.

**Comment by patsevanton** [comment]
I think create fork popular openvpn docker repo. For example: https://github.com/kylemanna/docker-openvpn
