### ISSUE TITLE
Unsupported options: no-multilib

### ISSUE THREAD

**Issue by Clodo76** [OpenVPN/openvpn-build#28]
If i try to compile with OpenSSL 1.1.0 and OpenVPN 2.3.12,
`***** Unsupported options: no-multilib`
`FATAL: Configure openssl`

In both Linux (Debian 8) and OS X. I try to replace it with without-multilib or disable-multilib without success.
Thanks for any feedback.

**Comment by chipitsine** [comment]
openssl-1.1 is not a "in place replacement" for openssl-1.0, you must also rewrite an application to work with openssl-1.1

you are welcome to provide pull request
