### ISSUE TITLE
PLAP not in released MSI 

### ISSUE THREAD

**Issue by autinerd** [OpenVPN/openvpn-build#285]
Hi,

I wanted to install the OpenVPN GUI with the PLAP module to try it out.

But although it was implemented here before the version 2.5.8-I603, in the released MSI https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.8-I603-amd64.msi it is not available. Is there a specific reason for that?

Thanks in advance.

**Comment by lstipakov** [comment]
The PLAP will be part of 2.6 release, you can try it out with the MSI snapshot from [here](https://build.openvpn.net/downloads/snapshots/github-actions/openvpn2/).

For 2.5 you would need to build/install the PLAP dll manually. You might find some information [here](https://github.com/OpenVPN/openvpn-gui/pull/518).

**Comment by autinerd** [comment]
Thank you very much, I will try it!
