### ISSUE TITLE
Typo in latest build for macOS

### ISSUE THREAD

**Issue by nowakommunikation** [OpenVPN/openvpn-build#287]
I'm not sure if this is the right place or if it is relevant at all, but when generating the RSA key, the message should read 

Generating an RSA private key

not "a RSA private..."

![unnamed](https://user-images.githubusercontent.com/44474606/204082694-c3c5657f-8cd5-4b50-a836-7afc15fd6604.jpg)

**Comment by lstipakov** [comment]
I believe it is something written by [OpenSSL](https://github.com/openssl/openssl/search?q=%22Generating+a+RSA%20private%20key%22&type=issues), not by OpenVPN.
