### ISSUE TITLE
centos 7    gcc: error: lz4-exe.o: 没有那个文件或目录

### ISSUE THREAD

**Issue by dylu9988** [OpenVPN/openvpn-build#292]
libtool: install: chmod 644 /home/jin/openvpn-build/generic/image/openvpn//lib/liblzo2.a
libtool: install: ranlib /home/jin/openvpn-build/generic/image/openvpn//lib/liblzo2.a
libtool: warning: remember to run 'libtool --finish //lib'
make[2]: 离开目录“/home/jin/openvpn-build/generic/tmp/lzo-2.10”
make[1]: 离开目录“/home/jin/openvpn-build/generic/tmp/lzo-2.10”
Build lz4
./configure --prefix=/ --libdir=//lib --host= --target= --build= --program-prefix='' --enable-shared
make[1]: 进入目录“/home/jin/openvpn-build/generic/tmp/lz4-1.9.3/lib”
compiling static library
creating library resource
gcc -DXXH_NAMESPACE=LZ4_ -O3   -c lz4.c lz4frame.c lz4hc.c xxhash.c
sed -e 's|@LIBLZ4@|liblz4|' \
         -e 's|@LIBVER_MAJOR@|1|g' \
         -e 's|@LIBVER_MINOR@|9|g' \
         -e 's|@LIBVER_PATCH@|3|g' \
          liblz4-dll.rc.in >liblz4-dll.rc
windres -i liblz4-dll.rc -o liblz4-dll.o
make[1]: windres: 没有那个文件或目录
make[1]: [Makefile:104：liblz4-dll.o] 错误 127 (已忽略）
ar rcs liblz4.a *.o
make[1]: 离开目录“/home/jin/openvpn-build/generic/tmp/lz4-1.9.3/lib”
make[1]: 进入目录“/home/jin/openvpn-build/generic/tmp/lz4-1.9.3/programs”
gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o bench.o bench.c
gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o datagen.o datagen.c
gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4cli.o lz4cli.c
gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_  -c -o lz4io.o lz4io.c
creating executable resource
sed -e 's|@PROGNAME@|lz4|' \
         -e 's|@LIBVER_MAJOR@|1|g' \
         -e 's|@LIBVER_MINOR@|9|g' \
         -e 's|@LIBVER_PATCH@|3|g' \
         -e 's|@EXT@|.exe|g' \
          lz4-exe.rc.in >lz4-exe.rc
windres -i lz4-exe.rc -o lz4-exe.o
make[1]: windres: 没有那个文件或目录
make[1]: [Makefile:80：lz4-exe.o] 错误 127 (已忽略）
gcc -O3   -I../lib -DXXH_NAMESPACE=LZ4_   ../lib/lz4.o ../lib/lz4frame.o ../lib/lz4hc.o ../lib/xxhash.o bench.o datagen.o lz4cli.o lz4io.o lz4-exe.o -o lz4.exe
gcc: error: lz4-exe.o: 没有那个文件或目录
make[1]: [Makefile:83：lz4] 错误 1 (已忽略）
make[1]: 离开目录“/home/jin/openvpn-build/generic/tmp/lz4-1.9.3/programs”
cp: 无法获取"programs/lz4.exe" 的文件状态(stat): 没有那个文件或目录
make: *** [Makefile:60：lz4-release] 错误 1
FATAL: make lz4
我手动进入/home/jin/openvpn-build/generic/tmp/lz4-1.9.3目录下，make是成功的。

**Comment by lstipakov** [comment]
Let's hope that someone using generic build system can help you. Meanwhile, if you build for Windows, have you considered using MSVC build system? It is maintained much better.

**Comment by selvanair** [comment]
You appear to be wanting to cross-compile for Windows on Linux but have configured for a native build. CHOST and CBUILD should be defined appropriately and have mingw-w64 installed.

Then something like below should work:

`CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build --use-depcache=64`

Replace `--save-depcache` by `--use-depcache` for subsequent builds if you want to reuse the dependency dlls built during the first run. See README for more details.

**Comment by selvanair** [comment]
Building for linux is much easier to do from openvpn repo or a release tarball. Download and unpack the latest release tarball, and do, for example 
`./configure --disable-lzo --disable-lz4 --disable-pkcs11`
`make`
That would require OpenSSL3 dev package for your distribution installed.

I wonder anyone still uses openvpn-build for anything but windows cross-compile. Note that your initial post showed an error of `windres` not found. `windres` is used only for Windows builds. Possibly native build using openvpn-build is broken.

**Comment by lstipakov** [comment]
We do run MinGW builds, but with GHA scripts: https://github.com/OpenVPN/openvpn/blob/master/.github/workflows/build.yaml#L38 

We should probably either:
 - add openvpn-build generic to CI
 - get rid of it, since no-one seem to be interested in maintaining it

**Comment by flichtenheld** [comment]
We have decided to remove the nsis/mingw buildsystem since it is not maintained anymore. Only the msi/msvc buildsystem will remain, unless someone steps up to maintain the other parts. This issue will be closed when the removal actually happens.

**Comment by flichtenheld** [comment]
Moving the MinGW builds of OpenVPN to use CMake+VCPKG. Support is already in master and will be backported to release/2.6. There is definitely no plan to address this in the context of "generic". So closing this issue.
