### ISSUE TITLE
Hard coded path in openvpn-plap-install.reg

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-build#297]
The dll path is set as `"C:\\Program Files\\OpenVPN\\bin\\libopenvpn_plap.dll"` but the dll may get copied elsewhere if the user chooses a different install path. As registering the dll from the GUI menu uses this reg file, we need to get the right install path in here. The uninstall file is not affected.

Would it be possible to edit this file or generate it during installation?

**Comment by lstipakov** [comment]
Yes, we would need a custom action for that. I'll take care of it.

**Comment by lstipakov** [comment]
Fixed in 2.6 beta2.
