### ISSUE TITLE
Double and tripple backslash in directory address resulting to No such file or directory

### ISSUE THREAD

**Issue by modfiles** [OpenVPN/openvpn-build#31]
Hi, 
I'm trying to compile openvpn using my raspberry pi (raspbian-jessie-lite) using the command 
`IMAGEROOT='pwd'/image-native ./build`
but i always end up having this issue 

> installing man3/d2i_SSL_SESSION.3
> i2d_SSL_SESSION.3 => d2i_SSL_SESSION.3
> installing man3/ssl.3
> SSL.3 => ssl.3
> created directory 'pwd/image-native/openvpn//bin'
> created directory 'pwd/image-native/openvpn///lib'
> created directory 'pwd/image-native/openvpn///lib/engines'
> created directory 'pwd/image-native/openvpn///lib/pkgconfig'
> created directory 'pwd/image-native/openvpn//include'
> created directory 'pwd/image-native/openvpn//include/openssl'
> created directory 'pwd/image-native/openvpn/etc'
> created directory 'pwd/image-native/openvpn/etc/ssl'
> created directory 'pwd/image-native/openvpn/etc/ssl/misc'
> created directory 'pwd/image-native/openvpn/etc/ssl/certs'
> created directory 'pwd/image-native/openvpn/etc/ssl/private'
> making install in crypto...
> make[1]: Entering directory '/home/pi/openvpn-build/generic/tmp/openssl-1.0.2h/crypto'
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/crypto.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/crypto.h': No such file or directory
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/opensslv.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/opensslv.h': No such file or directory
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/opensslconf.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/opensslconf.h': No such file or directory
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/ebcdic.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/ebcdic.h': No such file or directory
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/symhacks.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/symhacks.h': No such file or directory
> cp: cannot create regular file 'pwd/image-native/openvpn//include/openssl/ossl_typ.h': No such file or directory
> chmod: cannot access 'pwd/image-native/openvpn//include/openssl/ossl_typ.h': No such file or directory
> Makefile:117: recipe for target 'install' failed
> make[1]: *** [install] Error 1
> make[1]: Leaving directory '/home/pi/openvpn-build/generic/tmp/openssl-1.0.2h/crypto'
> Makefile:536: recipe for target 'install_sw' failed
> make: *** [install_sw] Error 1
> FATAL: make openssl

also experience those errors having double backslash in creating a directory resulting to `No such file or directory` when im cross compiling for windows 64bit using ubuntu 16.04 64bit but i was able to build and compile windows 32bit though.
trying to compile also for ubuntu 16.04 64bit using the same command to my raspberry pi will throw same error.

Compiling for ARM devices using the command 
`IMAGEROOT='pwd'/image-arm CHOST=arm-linux-gnueabi CBUILD=x86_64-pc-linux-gnu ./build`
in ubuntu 16.04 will result in libpam missing although i have installed libpam0g-dev

I've been googling for days already trying to resolve the issue and as much as possible, not asking the contributor but this is something i know i cant resolve just by googling. Hope you can shed a light on this issue

btw, im using this repo as source for openvpn client
https://github.com/schwabe/openvpn/tree/icsopenvpn

Regards,
modfiles 

Error in raspberry (raspbian-jessie-lite) trying to compile using the command `IMAGEROOT='pwd'/image-native ./build`
![raspberry](https://cloud.githubusercontent.com/assets/11314888/18662232/ff73cac8-7f4b-11e6-9cb8-163276627927.jpg)

Error in Ubuntu 16.04 LTS 64bit trying to compile using the command `IMAGEROOT='pwd'/image-arm CHOST=arm-linux-gnueabi CBUILD=x86_64-pc-linux-gnu ./build`
![screenshot from 2016-09-20 02-09-32](https://cloud.githubusercontent.com/assets/11314888/18664521/7a7aa152-7f55-11e6-9df2-86e5147d184a.png)

**Comment by mattock** [comment]
@modfiles : so this was a user error?

**Comment by modfiles** [comment]
@mattock unfortunately yes, it was an user error i did use `IMAGEROOT='pwd'` instead of `IMAGEROOT=`pwd``
