### ISSUE TITLE
Packages built by debian-sbuild don't have DCO enabled

### ISSUE THREAD

**Issue by flichtenheld** [OpenVPN/openvpn-build#333]
Since we copied the original rules files and --enable-dco is not enabled by default, it is not built in (except the bookworm package).

Reported here: https://forums.openvpn.net/viewtopic.php?t=35260#p110392

**Comment by flichtenheld** [comment]
Sadly most of the packages are built with --enable-iproute2 still. So --enable-dco is not a completely compatible change. We can probably enable DCO for the packages that do not use --enable-iproute2. This is Debian buster and newer and Ubuntu jammy and newer. For the others we need to think about how to make the switch.

**Comment by fixed77** [comment]
Ubuntu focal. Released OpenVPN **2.6.1**
enable_dco=no

**Comment by flichtenheld** [comment]
I don't think we care about DCO on Debian 9/10 or Ubuntu 18.04. All of these are not supported or almost out of support. So the real issue is really Ubuntu 20.04. Will need to discuss how to handle that. Potential options are:

1. Just enable DCO and disable iproute2 support on Ubuntu focal. This might break some setups?
2. Provide a new package on focal "openvpn-dco" which enables DCO while disabling iproute2. Still leave iproute2 enabled for default "openvpn" package on focal. This would be extra work and confusing but ensure that we do not break additional setups.
3. Ignore and just do not provide a DCO-enabled package for focal

**Comment by cron2** [comment]
Hi,

On Thu, Mar 16, 2023 at 02:34:39AM -0700, Frank Lichtenheld wrote:
> 1. Just enable DCO and disable iproute2 support on Ubuntu focal. This might break some setups?

I'd go this way.

--enable-iproute2 is something that became a "second class citizen"
in 2.5.0 with the introduction of sitnl - yes, there will be someone
who uses a custom binary to do this, but they can use the system provided
openvpn package then.  We ship the latest and greatest :-)

(Having an explanation text at package installation would be good,
though I have no idea how to do that for Debian packages)

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by flichtenheld** [comment]
>  (Having an explanation text at package installation would be good, though I have no idea how to do that for Debian packages) 

There is the NEWS.Debian mechanism which is intended for that. I will look into it.

**Comment by flichtenheld** [comment]
2.6.2 packages have been published. Now focal packages have DCO enabled as well
