### ISSUE TITLE
Make it possible to build for Windows without lz4

### ISSUE THREAD

**Issue by faern** [OpenVPN/openvpn-build#337]
It's currently not possible to cross compile from Linux to Windows without building and including lz4. We do not use or want compression and want to strip our OpenVPN binaries from all unused functionality. Can `openvpn-build` be made to respect `--disable-lz4`?

**Comment by lstipakov** [comment]
Cross-compilation has been removed from openvpn-build master, as we do not use it for building releases and we have no maintainer for it.

We have [mingw builds](https://github.com/OpenVPN/openvpn/blob/master/.github/workflows/build.yaml#L38) in GitHub actions for OpenVPN project which use `--disable-lz4`, maybe you can get some ideas from there.

**Comment by selvanair** [comment]
I haven't used openvpn-build/generic in a while, but I think the following should work :
`export EXTRA_OPENVPN_CONFIG="--disable-lz4 --disable-lzo"`
This is set in a script that calls `openvpn-build/generic/build`

These days I just cross-compile openvpn.exe directly from the git repo -- much easier once you have a setup to build all dependent dlls separately.

**Comment by cron2** [comment]
Hi,

On Thu, Feb 16, 2023 at 08:06:16AM -0800, Selva Nair wrote:
> These days I just cross-compile openvpn.exe directly from the git repo -- much easier once you have a setup to build all dependent dlls separately.

So do I.  I have a set of scripts to do the "preparation building" and
then I can just do "git pull --rebase ; make" in the openvpn repo -
much faster than the old approach.

I need to polish these and submit as a "new way" for openvpn-build...
so not everybody needs to re-invent this particular wheel.

gert
-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             ***@***.***

**Comment by faern** [comment]
Ah. Updated instructions on how to easiest/best cross compile to Windows would be awesome! :sparkles:

**Comment by flichtenheld** [comment]
CMake support for MinGW+VCPKG build is in OpenVPN master now.
