### ISSUE TITLE
EasyRSA-Start.bat PATH error

### ISSUE THREAD

**Issue by FreeBeing11** [OpenVPN/openvpn-build#352]
Hi,

Since few OpenVPN versions (2.6.2 tested), I have a bug with EasyRSA-Start.bat script, because the PATH is not set correctly (for openssl.exe, by example).

EasyRSA-Start.bat provided with OpenVPN 2.6.2 :
@echo OFF
rem Automatically set PATH to openssl.exe
FOR /F "tokens=2*" %%a IN ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN" /ve') DO set "PATH=%PATH%;%%b\bin"
bin\sh.exe bin\easyrsa-shell-init.sh

ut, the result is not good, because set command gives for PATH :
PATH='C:/Program Files/OpenVPN/easy-rsa;C:/Program Files/OpenVPN/easy-rsa/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Maxime\AppData\Local\Microsoft\WindowsApps;REG_SZ    C:\Program Files\OpenVPN\\bin'

(see the end REG_SZ C:\Program Files\OpenVPN\bin) the PATH is broken and mixed with a name of registry value.

So, to get EasyRSA works correctly, I changed the EasyRSA-Start.bat to that :
@echo OFF
rem Automatically set PATH to openssl.exe
set "PATH=%PATH%;C:\Program Files\OpenVPN\bin"
bin\sh.exe bin\easyrsa-shell-init.sh

Please, do you plan a fix for that ?

Thank you

**Comment by cron2** [comment]
Moving this to the openvpn-build repo, because it's something in the "build installer" process that is buggy, not "a bug in openvpn"

**Comment by shipitsin-ilia** [comment]
Interesting. I'll have a look

**Comment by lstipakov** [comment]
I have slightly different output (Finnish/English):

```
HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN
    (Default)    REG_SZ    C:\Program Files\OpenVPN\
```

**Comment by cron2** [comment]
But it's still "3 columns".  I guess the original poster has something like `(some thing) REG_SZ ...` with a blank in, so the parsing "give me field 3+" will then include REG_SZ...

Is there a way to change the FOR statement to do "give me all after REG_SZ" instead?

**Comment by lstipakov** [comment]
Here is an output from colleague's machine:

```
Microsoft Windows [Version 10.0.19044.2728]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\diach>REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE" /ve

HKEY_LOCAL_MACHINE\SOFTWARE
    (по умолчанию)    REG_SZ
```

I am not too much into batch, but let's try to find a solution.

**Comment by lstipakov** [comment]
@FreeBeing11 @chipitsine Could you try out [this](https://github.com/OpenVPN/openvpn-build/suites/12184201512/artifacts/643438272 ) build (don't forget to install EasyRSA component) and see if problem is solved for you?

**Comment by chipitsine** [comment]
Give me a day

**Comment by FreeBeing11** [comment]
> @FreeBeing11 @chipitsine Could you try out [this](https://github.com/OpenVPN/openvpn-build/suites/12184201512/artifacts/643438272) build (don't forget to install EasyRSA component) and see if problem is solved for you?

Hi Istipakov,

Thank you for this new OpenVPN build, with a new "EasyRSA-Start.bat" script.

I tried that on Windows 10 22H2 x64 (French), and it works, thank you ;)

With EasyRSA Shell, now I obtain this PATH with "set" command :
PATH='C:/Program Files/OpenVPN/easy-rsa;C:/Program Files/OpenVPN/easy-rsa/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Maxime\AppData\Local\Microsoft\WindowsApps;C:\Program Files\OpenVPN\bin\'

Now, PATH is right, and "openssl.exe" can be used directly.

Thanks a lot.
