### ISSUE TITLE
Windows sample configurations files with wrong EOL and blank lines

### ISSUE THREAD

**Issue by FreeBeing11** [OpenVPN/openvpn-build#358]
Hi,

On Windows, OpenVPN sample config files (server.ovpn and client.ovpn) have problems since few versions :

1) Macintosh (CR) EOL instead of Windows (CR LF) EOL.
(you can check that with Notepad++ editor, for example)
We must convert to Windows (CR LF), otherwise, OpenVPN don't start.

2) Too many blank lines into thoses files, even into comments

(Bug is there since few version, and still there in OpenVPN 2.6.3)

Thank you

**Comment by flichtenheld** [comment]
Moved this issue to openvpn-build since the issue is pretty clearly in the MSI build script

**Comment by flichtenheld** [comment]
2.6.3-I002 is now available with the fix
