### ISSUE TITLE
win11系统，编译生成msi安装包时出现错误

### ISSUE THREAD

**Issue by MythosMonkeyKing** [OpenVPN/openvpn-build#373]
PS D:\github\openvpn-build\windows-msi> .\build-and-package.ps1 -arch amd64
Building openvpn-gui x64
Preset CMake variables:

  CMAKE_BUILD_TYPE="Release"
  CMAKE_TOOLCHAIN_FILE:FILEPATH="D:\github\openvpn-build\src\vcpkg/scripts/buildsystems/vcpkg.cmake"

-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
All requested packages are currently installed.
Restored 0 package(s) from C:\Users\mythos\AppData\Local\vcpkg\archives in 288 us. Use --debug to see more details.
Total install time: 362 us
json-c provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(json-c CONFIG REQUIRED)
    target_link_libraries(main PRIVATE json-c::json-c json-c::json-c-static)

-- Running vcpkg install - done
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- Configuring done (30.4s)
-- Generating done (0.6s)
-- Build files have been written to: D:/github/openvpn-build/src/openvpn-gui/out/build/x64-release
MSBuild version 17.6.3+07e294721 for .NET Framework

  libopenvpn_plap.vcxproj -> D:\github\openvpn-build\src\openvpn-gui\out\build\x64-release\libopenvpn_plap.dll
  openvpn-gui.vcxproj -> D:\github\openvpn-build\src\openvpn-gui\out\build\x64-release\openvpn-gui.exe
  test_plap.vcxproj -> D:\github\openvpn-build\src\openvpn-gui\out\build\x64-release\test_plap.exe
MSBuild version 17.6.3+07e294721 for .NET Framework
生成启动时间为 2023/6/6 19:03:29。

     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”在节点 1 上(Build 个目标)。
     1>ValidateSolutionConfiguration:
         正在生成解决方案配置“Release|x64”。
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 6 上生成“D:\github\openvpn-build\src\openvpn\build\msvc\msvc-generate
       \msvc-generate.vcxproj”(2) (默认目标)。
     2>Build:
         nmake -f Makefile.mak all

         Microsoft (R) ����ά��ʵ�ù��� 14.36.32532.0 ��
         ��Ȩ���� (C) Microsoft Corporation��  ��������Ȩ����

                FOR /F %i IN ('where rst2html.py') DO python %i "D:\github\openvpn-build\src\openvpn\/doc/openvpn.8.rst" "D:\github\
         openvpn-build\src\openvpn\/doc/openvpn.8.html"
         INFO: Could not find files for the given pattern(s).
                python git-version.py D:\github\openvpn-build\src\openvpn\
         Content of D:\github\openvpn-build\src\openvpn\config-version.h hasn't changed
     2>已完成生成项目“D:\github\openvpn-build\src\openvpn\build\msvc\msvc-generate\msvc-generate.vcxproj”(默认目标)的操作。
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 3 上生成“D:\github\openvpn-build\src\openvpn\src\tapctl\tapctl.vcxpro
       j”(3) (默认目标)。
     3>InitializeBuildStatus:
         正在创建“x64\Release\tapctl.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       VcpkgTripletSelection:
         Using triplet "x64-windows" from "D:\github\openvpn-build\src\vcpkg\installed\x64-windows\"
         Using normalized configuration "Release"
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 5 上生成“D:\github\openvpn-build\src\openvpn\src\openvpnmsica\openvpn
       msica.vcxproj”(4) (默认目标)。
     4>InitializeBuildStatus:
         正在创建“x64\Release\openvpnmsica.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 2 上生成“D:\github\openvpn-build\src\openvpn\src\compat\compat.vcxpro
       j”(5) (默认目标)。
     5>InitializeBuildStatus:
         正在创建“x64\Release\compat.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 1 上生成“D:\github\openvpn-build\src\openvpn\src\openvpnserv\openvpns
       erv.vcxproj”(7) (默认目标)。
     7>InitializeBuildStatus:
         正在创建“x64\Release\openvpnserv.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
     3>ClCompile:
         所有输出均为最新。
       ResourceCompile:
         所有输出均为最新。
     4>VcpkgTripletSelection:
         Using triplet "x64-windows" from "D:\github\openvpn-build\src\vcpkg\installed\x64-windows\"
         Using normalized configuration "Release"
       ClCompile:
         所有输出均为最新。
     7>VcpkgTripletSelection:
         Using triplet "x64-windows" from "D:\github\openvpn-build\src\vcpkg\installed\x64-windows\"
         Using normalized configuration "Release"
     3>Link:
         所有输出均为最新。
     4>ResourceCompile:
         所有输出均为最新。
     3>Link:
         tapctl.vcxproj -> D:\github\openvpn-build\src\openvpn\x64-Output\Release\tapctl.exe
     7>ClCompile:
         所有输出均为最新。
     4>Link:
         所有输出均为最新。
         openvpnmsica.vcxproj -> D:\github\openvpn-build\src\openvpn\x64-Output\Release\libopenvpnmsica.dll
       FinalizeBuildStatus:
         正在删除文件“x64\Release\openvpnmsica.tlog\unsuccessfulbuild”。
         正在对“x64\Release\openvpnmsica.tlog\openvpnmsica.lastbuildstate”执行 Touch 任务。
     4>已完成生成项目“D:\github\openvpn-build\src\openvpn\src\openvpnmsica\openvpnmsica.vcxproj”(默认目标)的操作。
     7>ResourceCompile:
         所有输出均为最新。
     5>VcpkgTripletSelection:
         Using triplet "x64-windows" from "D:\github\openvpn-build\src\vcpkg\installed\x64-windows\"
         Using normalized configuration "Release"
       ClCompile:
         所有输出均为最新。
     3>FinalizeBuildStatus:
         正在删除文件“x64\Release\tapctl.tlog\unsuccessfulbuild”。
         正在对“x64\Release\tapctl.tlog\tapctl.lastbuildstate”执行 Touch 任务。
     3>已完成生成项目“D:\github\openvpn-build\src\openvpn\src\tapctl\tapctl.vcxproj”(默认目标)的操作。
     7>Link:
         所有输出均为最新。
         openvpnserv.vcxproj -> D:\github\openvpn-build\src\openvpn\x64-Output\Release\openvpnserv.exe
     5>Lib:
         所有输出均为最新。
         compat.vcxproj -> D:\github\openvpn-build\src\openvpn\x64-Output\Release\compat.lib
       AppLocalFromInstalled:
         pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\github\openvpn-build\src\vcpkg\scripts\buildsystems\msbuild\applocal.
         ps1" "D:\github\openvpn-build\src\openvpn\x64-Output\Release\compat.lib" "D:\github\openvpn-build\src\vcpkg\installed\x64-w
         indows\bin" "x64\Release\compat.tlog\compat.write.1u.tlog" "x64\Release\vcpkg.applocal.log"
     7>FinalizeBuildStatus:
         正在删除文件“x64\Release\openvpnserv.tlog\unsuccessfulbuild”。
         正在对“x64\Release\openvpnserv.tlog\openvpnserv.lastbuildstate”执行 Touch 任务。
     7>已完成生成项目“D:\github\openvpn-build\src\openvpn\src\openvpnserv\openvpnserv.vcxproj”(默认目标)的操作。
     5>AppLocalFromInstalled:
         'pwsh.exe' is not recognized as an internal or external command,
         operable program or batch file.
         命令“pwsh.exe -ExecutionPolicy Bypass -noprofile -File "D:\github\openvpn-build\src\vcpkg\scripts\buildsystems\msbuild\apploc
         al.ps1" "D:\github\openvpn-build\src\openvpn\x64-Output\Release\compat.lib" "D:\github\openvpn-build\src\vcpkg\installed\x6
         4-windows\bin" "x64\Release\compat.tlog\compat.write.1u.tlog" "x64\Release\vcpkg.applocal.log"”已退出，代码为 9009。
         "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -noprofile -File "D:\github\openvpn-bui
         ld\src\vcpkg\scripts\buildsystems\msbuild\applocal.ps1" "D:\github\openvpn-build\src\openvpn\x64-Output\Release\compat.lib"
          "D:\github\openvpn-build\src\vcpkg\installed\x64-windows\bin" "x64\Release\compat.tlog\compat.write.1u.tlog" "x64\Release\
         vcpkg.applocal.log"
       FinalizeBuildStatus:
         正在删除文件“x64\Release\compat.tlog\unsuccessfulbuild”。
         正在对“x64\Release\compat.tlog\compat.lastbuildstate”执行 Touch 任务。
     5>已完成生成项目“D:\github\openvpn-build\src\openvpn\src\compat\compat.vcxproj”(默认目标)的操作。
     1>项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(1)正在节点 4 上生成“D:\github\openvpn-build\src\openvpn\src\openvpn\openvpn.vcxp
       roj”(6) (默认目标)。
     6>InitializeBuildStatus:
         正在创建“x64\Release\openvpn.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
       VcpkgTripletSelection:
         Using triplet "x64-windows-ovpn" from "D:\github\openvpn-build\src\openvpn\src\openvpn\vcpkg_installed\x64-windows-ovpn\x64
         -windows-ovpn\"
         Using normalized configuration "Release"
       VcpkgInstallManifestDependencies:
       正在跳过目标“VcpkgInstallManifestDependencies”，因为所有输出文件相对于输入文件而言都是最新的。
       ClCompile:
         所有输出均为最新。
       ResourceCompile:
         所有输出均为最新。
       Link:
         所有输出均为最新。
         openvpn.vcxproj -> D:\github\openvpn-build\src\openvpn\x64-Output\Release\openvpn.exe
       FinalizeBuildStatus:
         正在删除文件“x64\Release\openvpn.tlog\unsuccessfulbuild”。
         正在对“x64\Release\openvpn.tlog\openvpn.lastbuildstate”执行 Touch 任务。
     6>已完成生成项目“D:\github\openvpn-build\src\openvpn\src\openvpn\openvpn.vcxproj”(默认目标)的操作。
     1>已完成生成项目“D:\github\openvpn-build\src\openvpn\openvpn.sln”(Build 个目标)的操作。

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:11.83
Skip signing binaries
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

D:\github\openvpn-build\windows-msi\build.wsf(165, 20) Microsoft JScript runtime error: Don't know how to build "..\src\openvpn\doc\openvpn.8.html".

Skip signing MSI
PS D:\github\openvpn-build\windows-msi>

**Comment by lstipakov** [comment]
Hi,

`D:\github\openvpn-build\windows-msi\build.wsf(165, 20) Microsoft JScript runtime error: Don't know how to build "..\src\openvpn\doc\openvpn.8.html".`

You need to install `rst2html`:

`python -m pip install --upgrade pip rst2html`

**Comment by MythosMonkeyKing** [comment]
> Hi,
> 
> `D:\github\openvpn-build\windows-msi\build.wsf(165, 20) Microsoft JScript runtime error: Don't know how to build "..\src\openvpn\doc\openvpn.8.html".`
> 
> You need to install `rst2html`:
> 
> `python -m pip install --upgrade pip rst2html`

Thank you very much. Your answer has solved the problem. 
I see that readme provides two methods:
① PS D:\github\openvpn-build\windows-msi> .\build-and-package.ps1 -arch amd64
② PS D:\github\openvpn-build\windows-msi> cscript.exe .\build.wsf all

I successfully built the MSI installation package using the first method, but the second method encountered the following error:

PS D:\github\openvpn-build\windows-msi> cscript.exe .\build.wsf all
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

D:\github\openvpn-build\windows-msi\build.wsf(165, 20) Microsoft JScript runtime error: Don't know how to build "..\src\openvpn\Win32-Output\Release\libcrypto-3.dll".

PS D:\github\openvpn-build\windows-msi>

**Comment by flichtenheld** [comment]
> Thank you very much. Your answer has solved the problem. I see that readme provides two methods: ① PS D:\github\openvpn-build\windows-msi> .\build-and-package.ps1 -arch amd64 ② PS D:\github\openvpn-build\windows-msi> cscript.exe .\build.wsf all

No, it does not actually describe two ways. build-and-package.ps1 is the wrapper script and the cscript call is one part of it. It doesn't really work without the other steps build-and-package.ps1 does like building openvpn and openvpn-gui. I have thought in the past about how to make that distinction clearer in the README, but didn't come up with something good.
