### ISSUE TITLE
Cross Compile with OpenSSL 3

### ISSUE THREAD

**Issue by FabioMenge** [OpenVPN/openvpn-build#407]
Cross compiling in the generic subdirectorie always worked for me. I just had to change to the right openSSL 1 Version in the build.vars file. Because OpenSSl 1 wont be recieving security fixes soon, i wanted to switch to OpenSSL 3.

Changing the build.vars to the newest OpenSSL 3 version results in the build script to stop when building openSSL.
Error Message: "Please supply arguments" https://github.com/openssl/openssl/blob/master/util/mkdef.pl#L51

Is it possible to cross compile with OpenSSL 3 or is there some way to fix it?
Thank you.

**Comment by flichtenheld** [comment]
The scripts in generic are not maintained anymore. It is probably possible to change them to support OpenSSL 3 but you would need to do that yourself. The current release/2.6 GHA file does a cross build of openvpn again OpenSSL 3 (https://github.com/OpenVPN/openvpn/blob/release/2.6/.github/workflows/build.yaml). In OpenVPN master we recently introduced a new CMake buildsystem that we use for Windows builds going forward. MinGW cross-builds are also possible with that. See https://github.com/OpenVPN/openvpn/blob/master/README.cmake.md. The plan is to port that back to release/2.6 soonish. It will probably be the only officially supported way of doing MinGW cross-builds in the forseeable future.

**Comment by selvanair** [comment]
To add to the above, here is quick way to cross-compile from the git repo.

From the root of the repo
```
mkdir build-win
cd build-win
autoreconf -ivf ../

DEP_ROOT=/home/selva/win32  # install prefix of cross-built openssl and pkcs11 helper libs and includes
export OPENSSL_LIBS="-L${DEP_ROOT}/lib -lssl -lcrypto"
export OPENSSL_CFLAGS="-I${DEP_ROOT}/include"
export PKCS11_HELPER_CFLAGS="-I${DEP_ROOT}/include"
export PKCS11_HELPER_LIBS="-L${DEP_ROOT}/lib -lpkcs11-helper"
export TAP_CFLAGS="-I${DEP_ROOT}/include"

../configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu --disable-lz4 --disable-lzo --enable-pkcs11 --enable-comp-stub
make
```
Adapt to suit your needs.

Executables will be in `src/openvpn/.libs/`, `src/openvpnmscia/.libs/` and `src/openvpnserv/.libs/`. You can copy them and the dependent dlls to the Windows machine or build the installer from those.

**Comment by FabioMenge** [comment]
Thank you for ur great help!

When i try to use the configure
../configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu --disable-lz4 --disable-lzo --enable-pkcs11 --enable-comp-stub
it gets interrupted by an error:
configure: error:  no tap header could be found.

Do i miss some source code or an installation?

**Comment by flichtenheld** [comment]
> Thank you for ur great help!
> 
> When i try to use the configure ../configure --host=x86_64-w64-mingw32 --build=x86_64-pc-linux-gnu --disable-lz4 --disable-lzo --enable-pkcs11 --enable-comp-stub it gets interrupted by an error: configure: error: no tap header could be found.
> 
> Do i miss some source code or an installation?

You need the `tap-windows.h` from tap-windows6.

**Comment by FabioMenge** [comment]
I got the File from
https://github.com/OpenVPN/tap-windows6/blob/master/src/tap-windows.h

I tried to copy the file to different directories, but the Error still persists.

**Comment by s5410s** [comment]
> Is it possible to cross compile with OpenSSL 3 or is there some way to fix it? Thank you.

I fixed this script.  It's work for me

[build-openssl3.diff.txt](https://github.com/OpenVPN/openvpn-build/files/12308269/build-openssl3.diff.txt)

**Comment by FabioMenge** [comment]
You are my personal Hero. That worked perfectly!
