### ISSUE TITLE
HKCU\Software\Microsoft\Windows\CurrentVersion\Run  key is not removed during uninstall

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#51]
if someone checks "Launch GUI on Windows startup", that setting is not removed after uninstall
it will lead to error (Windows will attempt to start missing openvpn-gui.exe)

**Comment by selvanair** [comment]
As discussed under PR 55, the last commit there handles this. 

However, user's configs in their profile and HKCU\Software\OpenVPN-GUI key will not be removed. As the latter contains customizations and saved usernames etc., its better preserved especially if the uninstall is a prelude to a re-installing a new version. 

We can add some more sophisticated logic to this if users complain of the left behind registry key.

**Comment by mattock** [comment]
@selvanair : I agree we should not remove user-specific settings at uninstall. We reached the same conclusion as you have  in the past, when we designed the NSIS installer for OpenVPN-GUI. The installer is obviously no longer needed, but the logic is still valid.

**Comment by chipitsine** [comment]
it seems that active setup feature resolves that ?

**Comment by selvanair** [comment]
Yes this may now be closed.
