### ISSUE TITLE
tap driver is not removed on uninstall

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#66]
while installer says "removing TAP...", tap driver is not actually uninstalled

how to reproduce

- install openvpn
- uninstall openvpn

**Comment by selvanair** [comment]
Though I don't know if/why this happens, uninstalling TAP when OpenVPN is uninstalled is not always desired. 

What if TAP was independently installed by the user? Either we should remember whether TAP was installed as a part of OpenVPN and offer to remove it only then or leave it installed.  I would say just leave it installed just as we do with NET 4.0 even if it was added by our installer.

**Comment by chipitsine** [comment]
what is funny about .net ... if you install openvpn on "just installed russian win7", it installs .net without reboot, but when you choose "just installed english win7", reboot is required :-)

**Comment by chipitsine** [comment]
I could forgot to wrap tap uninstall with "RunningX64", I'll test this on x86 and x64

**Comment by chipitsine** [comment]
it is removed on both x86 and x64.
it stays in control panel for a while.
