### ISSUE TITLE
probably wrong order of openvpnserv2.exe and TAP installation

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#67]
https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L283

openvpnserv2.exe depends on "tap0901", however, TAP driver is installed **after** openvpnserv2.exe

**Comment by selvanair** [comment]
The  service is started after TAP is installed so should be fine. IIRC, this has been discussed in the past and service start was moved to where it is now.

**Comment by chipitsine** [comment]
does sc.exe allow creation of service dependent on nonexistent service/driver ?

**Comment by selvanair** [comment]
Yes, "sc config servicename depend= some-nonsense" will work as long as
servicename is valid. The dependency gets checked only when the service is started.

**Comment by chipitsine** [comment]
earlier TAP required a reboot after install. is it the reason to install it on the last stage?

**Comment by selvanair** [comment]
The current order works so why bother. Anyway the user can opt to not
install TAP (say already installed and do not want to re-install) so it
should work in either order. Of course starting the service will fail if
TAP is not found and the logs will show it.

We do make sure that the service is started at the end of the installation,
which, I think, is the correct way to do it, independent of dependency on
TAP etc.

**Comment by chipitsine** [comment]
the order is ok. I apologies for the issue.
