### ISSUE TITLE
pay more attention to .net installer

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#68]
if I install openvpn on "just installed russian win7 sp1 x86_64", it installs .net without reboot.

but if I install openvpn on "just installed english win7 x86_64" (the same, but without sp1), .net installer suggest reboot (which can be avoided, and actually is not desirablt here)

we should tweak .net installer to make it not rebooting (it is easy to reproduce, just install on win7 without sp1)

**Comment by selvanair** [comment]
In our current approach net installer runs independently so we assume it "knows best" and the user can decide to reboot or not. That was the main reason for doing it this way. So, I would say just leave it alone and let the user decide. We cannot possibly figure out all combinations where net installer may wrongly suggest a reboot if that is the case. 

Those who do not enjoy rebooting anyway runs some unix clone :)

**Comment by chipitsine** [comment]
well, reboot can happen "right during installation", current installer cannot handle "resuming installation after reboot", probably we should add "RunOnce" registry key.

or leave resuming up to user.

**Comment by selvanair** [comment]
NET install is started after finishing all tasks except FINISH PAGE which shows the README, so even if the user accepts to reboot nothing much is lost isn't it? Only lay users will reboot without completing the ongoing installer dialog, and anyway the README is too complex for most users.

**Comment by chipitsine** [comment]
README is complex, I agree on that. "Getting started" wizard  https://github.com/OpenVPN/openvpn-gui/issues/115 seems to be more friendly.

after implementing that we can stop showing README anymore


as for "how much is lost", the most missing thing is "uninstall information" in control panel

**Comment by selvanair** [comment]
Can we move net install to the finish page? Then nothing will get lost.

**Comment by chipitsine** [comment]
after uninstall information is written ?

I never tried that.

**Comment by flichtenheld** [comment]
windows 7 only issue?
