### ISSUE TITLE
Build an exe without installer

### ISSUE THREAD

**Issue by Herz3h** [OpenVPN/openvpn-build#71]
Hello,

Is there a way to build portable openvpn (aka without installer) with these scripts ?

**Comment by chipitsine** [comment]
What is use case?

**Comment by Herz3h** [comment]
I want to integrate openvpn into a GUI app to connect to an openvpn server.

**Comment by chipitsine** [comment]
By using theese scripts you can build openvpn.exe  and bundle it with whatever you wish.

**Comment by Herz3h** [comment]
Oh ok nice thank you !

**Comment by mattock** [comment]
@Herz3h : after building the installer you will find all the produced files (executables, libraries) under windows-nsis/tmp.
