### ISSUE TITLE
disable save-passwords

### ISSUE THREAD

**Issue by selvanair** [OpenVPN/openvpn-build#75]
With this feature proposed for the GUI, shall we add the registry key during install (set to 0, i.e., save password enabled by default) and also provide an option to set it to 1 (i.e., save password disabled) ?

Adding the key at install time has advantage that admins need not consult README to see how exactly to spell the key. Providing an option to set/unset during install is also nice, but it adds one more section (though hidden under the Advanced options).

Thoughts?

**Comment by chipitsine** [comment]
Installer option?

**Comment by mattock** [comment]
An installer option / new section would be easier from deployment perspective for admins who don't use configuration management tools (=the large majority).

**Comment by chipitsine** [comment]
this issue might be closed after PR#77 ?

**Comment by selvanair** [comment]
Implemented in PR #77
