### ISSUE TITLE
move openvpn-gui management into gui section ?

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#76]
should we move https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L182-L199  to https://github.com/OpenVPN/openvpn-build/blob/master/windows-nsis/openvpn.nsi#L371 ?

we should stop running openvpn-gui if and only if openvpn-gui is selected for install, right ?

**Comment by selvanair** [comment]
Stopping the GUI each time after asking the user is required. Otherwise when we stop the interactive service any connections started by the GUI will abnormally terminate.
