### ISSUE TITLE
Enable cron build on travis-ci

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#83]
@mattock , can you please enable daily cron builds at travis-ci ?

it can be done only at web interface, I beleive it is somewhat useful (especially for catching error on snapshot builds)

**Comment by mattock** [comment]
Is the idea to  catch errors in Travis-generated VMs/containers? For example when OS-level packages get updated and break our build.

**Comment by chipitsine** [comment]
travis-ci builds are triggered by github push events to openvpn/openvpn-build repo, currently builds are not triggered if openvpn/openvpn repo changed.

idea is to catch errors that come from openvpn/openvpn repo

**Comment by chipitsine** [comment]
it would be better to move openvpn-build into openvpn/openvpn repo, but I think that idea will not meet enough support from the community

**Comment by mattock** [comment]
Oh yes, that makes sense. Travis now does an automatic build every day.

**Comment by chipitsine** [comment]
there're might be an idea to report only failed builds (it might be tuned in .travis.yml)
if there'll be too much "build success" emails, we can address it

**Comment by mattock** [comment]
The reasons why we originally split OpenVPN into separate subprojects such as openvpn-build were

* Allow a new communities to form around subprojects
* Allow per-subproject patch handling procedures

We would not be doing this development via PRs if OpenVPN/openvpn-build was part of OpenVPN/openvpn :smile: . Also, a small developer community has formed around each subproject (openvpn-build, openvpn-gui, tap-windows6). So our "split to subprojects" approach has worked quite well.
