### ISSUE TITLE
http://build.openvpn.net/downloads/snapshots/openvpn-2.4.0.tar.gz is missing

### ISSUE THREAD

**Issue by chipitsine** [OpenVPN/openvpn-build#84]
https://ci.appveyor.com/project/chipitsine/openvpn-build/build/cygwin-24/job/3kvsxkn670ag2lar#L414

what if we switch to "github releases" instead of storing files on http://build.openvpn.net ?

**Comment by mattock** [comment]
Fixed. I had to remove old snapshot installers to free up disk space, and the tar.gz got removed by accident. I'm going to setup an automated reusable cleanup script to ensure the problem does not reappear. I'm not too keen to switching to GitHub releases, as I need to push the release files+signatures to our primary download server anyways, and pushing to build.openvpn.net comes as a bonus.

That said, for snapshot builds GitHub would make sense. Can we make Travis produce a snapshot Windows installer for each commit?

**Comment by chipitsine** [comment]
travis builds are triggered by webhook.
I'm not sure we can fire "openvpn/openvpn-build" run for "openvpn/openvpn" push event

I'll have a look

**Comment by mattock** [comment]
Building openvpn-build on push to OpenVPN/openvpn is probably _possible_ with webhooks, but not trivial to accomplish. I think "build once per day" is good enough and will catch errors quickly enough. If you want to tinker with this, though, I'm not holding you back, though :smile:.
