### ISSUE TITLE
Windows-nsis error

### ISSUE THREAD

**Issue by modfiles** [OpenVPN/openvpn-build#98]
Im tryin to compile Windows NSIS 32- and 64-bit installers but I always encounter this issue and I have no idea how to fix this and even after googling for possible fix

> Copying documents
Copying sources
Cleaning empty directories
Packing images
find: ‘tmp/installer/openvpn/share/doc/*’: No such file or directory
xargs: unix2dos: No such file or directory
FATAL: unix2dos
FATAL: pack installer >&2
User@HP-Pavilion-g6:~/Desktop/openvpn-build/windows-nsis$

**Comment by chipitsine** [comment]
unix2dos is missing. 

Can you try "which unix2dos" ?

**Comment by modfiles** [comment]
sorted it out by using
`apt-get install dos2unix` instead of `apt-get install unix2dos`
