### ISSUE TITLE
The situation needs to change

### ISSUE THREAD

**Issue by huanghe2015** [OpenVPN/openvpn-build#99]
With increasing popularity of your project,the GFW which has been built in mainland China has reset your software's network flow more frequent.Is there any method to avoid it?

**Comment by chipitsine** [comment]
there's https://github.com/jlund/streisand

it is not focused on bypassing GFW, however, it is discussed in issues very often
some of it's components (like openconnect or wireguard) are known to bypass GFW

**Comment by mattock** [comment]
@huanghe2015 : some commercial VPN providers have tools for circumventing the GFW. There are also ways to [obfuscate OpenVPN traffic](https://community.openvpn.net/openvpn/wiki/TrafficObfuscation) in hopes of getting it through the GFW.

The OpenVPN project has made the decision _not_ to include any obfuscation in OpenVPN core, as we would not have the resources to keep it updated.
